name: generate tests demo

on:
  pull_request:
    branches: [main]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set path variable
      id: set-path
      run: echo "::set-output name=path::shopping_cart"

    - name: Install gocodeo
      run: pip install gocodeo==0.0.0.1
      
    - name: Generating test cases
      run: |
        echo "${{ secrets.secret }}" | gocodeo-advanced generate ${{ steps.set-path.outputs.path }}
        
    - name: Check if branch exists
      run: git fetch origin feature/demo:feature/demo && git checkout feature/demo

    - name: Commit and push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --local user.email "soumendraroman@gmail.com"
        git config --local user.name "Soumendraprasad"
        git checkout feature/demo
        git pull origin feature/demo
        git add ${{ steps.set-path.outputs.path }}
        git commit -m "Add generated test cases"
        git push origin HEAD:${{ github.event.pull_request.head.ref }}
    - name: Installing Packages
      run: pip install coverage  psutil memory_profiler

    - name: Executing the generated test cases
      run: |
        export PYTHONPATH="$PWD"
        cd shopping_cart
        python table.py
        coverage run -m unittest discover -s gocodeo_tests|| true
    - name: Coverage Report
      run: coverage report
