name:  generate tests gocodeo

on:
  pull_request:
    branches: [main]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GoCodeo CLI
      id: set-path
      run: |
       echo "::set-output name=path::shopping_cart"
       pip install gocodeo==0.0.0.1 coverage  psutil memory_profiler

    - name: Generate test cases
      run: |
        echo "${{ secrets.secret }}" | gocodeo-advanced generate ${{ steps.set-path.outputs.path }}

    - name: Commit changes to PR
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git fetch origin feature/cli:feature/cli && git checkout feature/cli
        git config --local user.email "soumendraroman@gmail.com"
        git config --local user.name "Soumendraprasad"
        git checkout feature/cli
        git pull origin feature/cli
        git add ${{ steps.set-path.outputs.path }}
        git commit -m "Add generated test cases"
        git push origin HEAD:${{ github.event.pull_request.head.ref }}

    - name: Execute the generated test cases
      run: |
        export PYTHONPATH="$PWD"
        cd shopping_cart
        python table.py
        coverage run -m unittest discover -s gocodeo_tests|| true
        coverage report
